#!/bin/bash
#
# Pre commit hook to generate keymap-drawer files for corne_choc_pro

HAS_KEYMAP=`which keymap 2> /dev/null`

function source_home_file {
  file="$HOME/$1"
  [ -f "${file}" ] && source "${file}"
}

if [ -z "$HAS_KEYMAP" ]; then
  source_home_file ".bash_profile" || source_home_file ".zshrc" || source_home_file ".bashrc" || true
fi

KEYMAP=`which keymap 2> /dev/null`

set -euo pipefail

"$KEYMAP" -c ./keymap-drawer.config.yaml parse -z ./config/corne_choc_pro.keymap -o keymap-drawer/corne_choc_pro.yaml
"$KEYMAP" -c ./keymap-drawer.config.yaml draw -j config/corne_choc_pro.json keymap-drawer/corne_choc_pro.yaml >keymap-drawer/corne_choc_pro.svg

"$KEYMAP" -c ./keymap-drawer.config.yaml parse -z ./config/redox.keymap -o keymap-drawer/redox.yaml
"$KEYMAP" -c ./keymap-drawer.config.yaml draw keymap-drawer/redox.yaml >keymap-drawer/redox.svg

git add keymap-drawer/*.yaml keymap-drawer/*.svg